SNOWFLAKE_USER = "THAMARAI211221"
SNOWFLAKE_PASSWORD = "Thamarai@211221"
SNOWFLAKE_ACCOUNT = "JZZZRYX-GY72350"
OPENAI_API_KEY = "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"